services:
  bokses:
    image: nginx:alpine
    container_name: bokses
    restart: unless-stopped
    ports:
      - "8743:80"
    volumes:
      - /home/third/bokses/web:/usr/share/nginx/html:ro
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - bokses-api

  bokses-api:
    build:
      context: ./backend
    container_name: bokses-api
    restart: unless-stopped
    volumes:
      - bokses-data:/data

volumes:
  bokses-data:
