#!/usr/bin/env bash
# Runs the test suite with coverage, prints a per-file report, and fails if
# total line coverage is below MIN_COVERAGE (percent, default 0).
#
#   tool/coverage.sh                      # local run
#   MIN_COVERAGE=60 tool/coverage.sh      # enforce a floor
#   tool/coverage.sh --reporter=github    # extra args go to `flutter test`
#
# Coverage from `flutter test` only lists files some test imports, so a file
# with no tests would silently vanish from the total instead of counting as
# 0%. To avoid that, a throwaway test importing every lib/ file is generated
# for the run and deleted afterwards.
set -euo pipefail

cd "$(dirname "$0")/.."

MIN_COVERAGE="${MIN_COVERAGE:-0}"
HELPER=test/coverage_helper_test.dart
LCOV=coverage/lcov.info

cleanup() { rm -f "$HELPER"; }
trap cleanup EXIT

# ── 1. Import every library so untested files still count ─────────────────
# *_web.dart files use dart:js_interop and cannot load on the Dart VM that
# `flutter test` runs on, so they are left out.
{
  echo '// GENERATED by tool/coverage.sh — do not commit.'
  echo '// ignore_for_file: unused_import'
  find lib -name '*.dart' ! -name '._*' ! -name '*_web.dart' | LC_ALL=C sort |
    sed -e 's#^lib/#import '"'"'package:bokses/#' -e 's#$#'"'"';#'
  echo "import 'package:flutter_test/flutter_test.dart';"
  echo "void main() => test('all libraries load', () {});"
} > "$HELPER"

# ── 2. Run the tests ──────────────────────────────────────────────────────
# Test files are listed explicitly: on exFAT/FAT drives macOS writes a
# `._foo_test.dart` beside every file, and the runner hangs trying to load it.
TEST_FILES=()
while IFS= read -r f; do TEST_FILES+=("$f"); done \
  < <(find test -name '*_test.dart' ! -name '._*' | LC_ALL=C sort)

set +e
flutter test --coverage "$@" "${TEST_FILES[@]}"
TEST_STATUS=$?
set -e

if [[ ! -f "$LCOV" ]]; then
  echo "No coverage data was written to $LCOV." >&2
  [[ $TEST_STATUS -ne 0 ]] && exit "$TEST_STATUS" || exit 1
fi

# ── 3. Report ─────────────────────────────────────────────────────────────
# lcov: SF = source file, LF = lines found, LH = lines hit.
REPORT=$(awk -F: '
  /^SF:/ { file = substr($0, 4) }
  /^LF:/ { lf[file] = $2; total_lf += $2 }
  /^LH:/ { lh[file] = $2; total_lh += $2 }
  END {
    for (f in lf) {
      pct = lf[f] ? 100 * lh[f] / lf[f] : 100
      printf "%6.1f%%  %5d / %-5d  %s\n", pct, lh[f], lf[f], f | "sort -n"
    }
    close("sort -n")
    printf "TOTAL %.1f %d %d\n", total_lf ? 100 * total_lh / total_lf : 0, total_lh, total_lf
  }' "$LCOV")

FILES=$(printf '%s\n' "$REPORT" | grep -v '^TOTAL ')
read -r _ TOTAL HIT FOUND <<< "$(printf '%s\n' "$REPORT" | grep '^TOTAL ')"

echo
echo "Coverage by file (lowest first):"
printf '%s\n' "$FILES"
echo
echo "Total line coverage: ${TOTAL}% (${HIT} / ${FOUND} lines), minimum ${MIN_COVERAGE}%"

PASSED=$(awk -v t="$TOTAL" -v m="$MIN_COVERAGE" 'BEGIN { print (t + 0 >= m + 0) ? 1 : 0 }')

if [[ -n "${GITHUB_STEP_SUMMARY:-}" ]]; then
  {
    echo "## Test coverage"
    echo
    echo "**${TOTAL}%** of lines covered (${HIT} / ${FOUND}) — minimum **${MIN_COVERAGE}%** $([[ $PASSED == 1 ]] && echo '✅' || echo '❌')"
    echo
    echo "<details><summary>Coverage by file (lowest first)</summary>"
    echo
    echo '```'
    printf '%s\n' "$FILES"
    echo '```'
    echo "</details>"
  } >> "$GITHUB_STEP_SUMMARY"
fi

if [[ $TEST_STATUS -ne 0 ]]; then
  echo "Tests failed (exit $TEST_STATUS)." >&2
  exit "$TEST_STATUS"
fi

if [[ $PASSED != 1 ]]; then
  echo "Coverage ${TOTAL}% is below the ${MIN_COVERAGE}% minimum." >&2
  exit 1
fi
